export const EXTENSION_MESSAGE = {
  AUTH_TOKEN: "EASYSUBMIT_AUTH_TOKEN",
  GET_AUTH: "EASYSUBMIT_GET_AUTH",
  SAVE_JOB: "EASYSUBMIT_SAVE_JOB",
  UPDATE_JOB_FIELDS: "EASYSUBMIT_UPDATE_JOB_FIELDS",
  GET_COVER_LETTER_BODY: "EASYSUBMIT_GET_COVER_LETTER_BODY",
  SAVE_COVER_LETTER: "EASYSUBMIT_SAVE_COVER_LETTER",
  GET_RESUME_FORM: "EASYSUBMIT_GET_RESUME_FORM",
  SAVE_RESUME_FORM: "EASYSUBMIT_SAVE_RESUME_FORM",
  RUN_PIPELINE: "EASYSUBMIT_RUN_PIPELINE",
  START_APPLY: "EASYSUBMIT_START_APPLY",
  JOB_STATUS: "EASYSUBMIT_JOB_STATUS",
  GET_CONFIG: "EASYSUBMIT_GET_CONFIG",
  GET_RESUME_PROFILES: "EASYSUBMIT_GET_RESUME_PROFILES",
  FORCE_SHOW_CARD: "EASYSUBMIT_FORCE_SHOW_CARD",
  GET_TAB_STATUS: "EASYSUBMIT_GET_TAB_STATUS",
  GET_JOB_STATS: "EASYSUBMIT_GET_JOB_STATS",
  OPEN_DASHBOARD: "EASYSUBMIT_OPEN_DASHBOARD",
  COMPLETE_AUTOFILL: "EASYSUBMIT_COMPLETE_AUTOFILL",
  GET_FILL_DATA: "EASYSUBMIT_GET_FILL_DATA",
  GET_RESUME_PDF: "EASYSUBMIT_GET_RESUME_PDF",
  GET_COVER_LETTER_PDF: "EASYSUBMIT_GET_COVER_LETTER_PDF",
  GET_RESUME_DOCX: "EASYSUBMIT_GET_RESUME_DOCX",
  GET_COVER_LETTER_DOCX: "EASYSUBMIT_GET_COVER_LETTER_DOCX",
  GET_DOCUMENT_PREVIEW: "EASYSUBMIT_GET_DOCUMENT_PREVIEW",
  ENHANCE_DOCUMENT: "EASYSUBMIT_ENHANCE_DOCUMENT",
  GET_APPLICATION_ANSWERS: "EASYSUBMIT_GET_APPLICATION_ANSWERS",
  CAPTURE_APPLICATION_ANSWERS: "EASYSUBMIT_CAPTURE_APPLICATION_ANSWERS",
  UPDATE_USER_PREFS: "EASYSUBMIT_UPDATE_USER_PREFS",
  MARK_APPLIED: "EASYSUBMIT_MARK_APPLIED",
  GET_REALTIME_TOKEN: "EASYSUBMIT_GET_REALTIME_TOKEN",
  PING: "EASYSUBMIT_PING",
  CAPTURE_JOB: "EASYSUBMIT_CAPTURE_JOB",
  TAILOR_JOB_ASYNC: "EASYSUBMIT_TAILOR_JOB_ASYNC",
  GET_PIPELINE_DEBUG: "EASYSUBMIT_GET_PIPELINE_DEBUG",
  JOB_ARCHIVED: "EASYSUBMIT_JOB_ARCHIVED",
  GET_KEYWORD_GAP: "EASYSUBMIT_GET_KEYWORD_GAP",
  FETCH_GREENHOUSE_EMBEDDED: "EASYSUBMIT_FETCH_GREENHOUSE_EMBEDDED",
} as const;

export const STORAGE_KEYS = {
  authToken: "easysubmit_auth_token_v1",
  apiBaseUrl: "easysubmit_api_base_url_v1",
  cardPosition: "easysubmit_card_position_v1",
  cardCollapsed: "easysubmit_card_collapsed_v1",
  selectedProfileId: "easysubmit_selected_profile_id_v1",
  extensionId: "easysubmit_extension_id_v1",
  pendingApplyJobId: "easysubmit_pending_apply_job_id_v1",
  aiEnabled: "easysubmit_ai_enabled_v1",
} as const;

/** Sent on every extension → dashboard API request (`manifest.version`). */
export const EXTENSION_VERSION_HEADER = "X-Extension-Version";

/** Client-side enhance wait in extension content script (matches dashboard default). */
export const EXTENSION_ENHANCE_TIMEOUT_MS = 90_000;
