/** Common technical skills for deterministic resume scanning (no AI). */
export const TECH_SKILLS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Golang",
  "Rust",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Scala",
  "R",
  "MATLAB",
  "Dart",
  "Elixir",
  "React",
  "React Native",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Ruby on Rails",
  "Laravel",
  ".NET",
  "ASP.NET",
  "GraphQL",
  "REST",
  "gRPC",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "SASS",
  "Webpack",
  "Vite",
  "Babel",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "DynamoDB",
  "Firebase",
  "Supabase",
  "AWS",
  "Azure",
  "GCP",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "CI/CD",
  "GitHub Actions",
  "Jenkins",
  "Linux",
  "Bash",
  "Shell",
  "Nginx",
  "Apache",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Confluence",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Agile",
  "Scrum",
  "Kanban",
  "Jest",
  "Cypress",
  "Playwright",
  "Selenium",
  "PyTest",
  "JUnit",
  "Mocha",
  "Chai",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "scikit-learn",
  "Pandas",
  "NumPy",
  "Spark",
  "Hadoop",
  "Kafka",
  "RabbitMQ",
  "SQL",
  "NoSQL",
  "SQLite",
  "Prisma",
  "TypeORM",
  "Sequelize",
  "OpenAI",
  "LangChain",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "Data Analysis",
  "Tableau",
  "Power BI",
  "Excel",
  "Snowflake",
  "dbt",
  "Airflow",
  "Microservices",
  "System Design",
  "OAuth",
  "JWT",
  "WebSockets",
  "Solidity",
  "Blockchain",
  "Ethereum",
  "Unity",
  "Unreal Engine",
  "iOS",
  "Android",
  "Xcode",
  "Android Studio",
  "Flutter",
  "Objective-C",
  "Assembly",
  "Haskell",
  "Clojure",
  "Perl",
  "Lua",
  "SAP",
  "Salesforce",
  "Shopify",
  "WordPress",
  "Contentful",
  "Sanity",
  "Storybook",
  "ESLint",
  "Prettier",
  "Turborepo",
  "Nx",
  "Monorepo",
  "Redux",
  "Zustand",
  "MobX",
  "Recoil",
  "TanStack Query",
  "React Query",
  "SWR",
  "Apollo",
  "tRPC",
  "Socket.io",
  "WebRTC",
  "Three.js",
  "D3.js",
  "Mapbox",
  "Leaflet",
  "Stripe",
  "Twilio",
  "SendGrid",
  "Segment",
  "Mixpanel",
  "Amplitude",
  "Datadog",
  "Sentry",
  "New Relic",
  "Prometheus",
  "Grafana",
  "Splunk",
  "ELK",
  "Logstash",
  "Kibana",
  "Helm",
  "ArgoCD",
  "Pulumi",
  "CloudFormation",
  "Lambda",
  "EC2",
  "S3",
  "RDS",
  "CloudFront",
  "Route 53",
  "VPC",
  "IAM",
  "BigQuery",
  "Cloud Run",
  "Cloud Functions",
  "App Engine",
  "Heroku",
  "Vercel",
  "Netlify",
  "Railway",
  "Render",
  "Fly.io",
] as const;

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Scan resume text against the local skill dictionary (case-insensitive, word-aware). */
export function extractSkillsFromText(text: string): string[] {
  const normalized = text.toLowerCase();
  const found = new Set<string>();

  for (const skill of TECH_SKILLS) {
    const pattern = new RegExp(`\\b${escapeRegExp(skill.toLowerCase())}\\b`, "i");
    if (pattern.test(normalized)) {
      found.add(skill);
    }
  }

  return Array.from(found).sort((a, b) => a.localeCompare(b));
}
