-- AI engine: daily quotas, source preference, terms acceptance
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "aiSourcePreference" TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "aiEnhancementsToday" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "aiCallsToday" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "aiQuotaResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMP(3);
