// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const shellDatabaseUrl = process.env.DATABASE_URL;

dotenv.config({ path: ".env" });
dotenv.config({ path: ".env.local", override: true });

// Vercel / CI inject DATABASE_URL directly — only fall back to shell when files omit it.
if (!process.env.DATABASE_URL && shellDatabaseUrl) {
  process.env.DATABASE_URL = shellDatabaseUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx --yes tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
