// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const shellDatabaseUrl = process.env.DATABASE_URL;

dotenv.config({ path: ".env" });
dotenv.config({ path: ".env.local", override: true });

if (shellDatabaseUrl) {
  process.env.DATABASE_URL = shellDatabaseUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
