// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const shellDatabaseUrl = process.env.DATABASE_URL?.trim() || "";
const shellDirectUrl = process.env.DIRECT_URL?.trim() || "";

dotenv.config({ path: ".env" });
dotenv.config({ path: ".env.local", override: true });

// Vercel env run / CI / export wins over .env.local (local dev uses .env.local when unset).
if (shellDatabaseUrl) {
  process.env.DATABASE_URL = shellDatabaseUrl;
}
if (shellDirectUrl) {
  process.env.DIRECT_URL = shellDirectUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx --yes tsx prisma/seed.ts",
  },
  datasource: {
    // DIRECT_URL bypasses PgBouncer for migrations (advisory locks require a direct connection).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
