/** Static dictionary for Identity Phase job-title autocomplete. */
export const POPULAR_ROLES = [
  "Account Executive",
  "Account Manager",
  "AI Engineer",
  "Android Developer",
  "Application Developer",
  "Associate Product Manager",
  "Automation Engineer",
  "Back End Developer",
  "Benefits Administrator",
  "Biomedical Engineer",
  "Brand Manager",
  "Business Analyst",
  "Business Development Manager",
  "Business Intelligence Analyst",
  "Chief Compliance Officer",
  "Chief Customer Officer",
  "Chief Customer Success Officer",
  "Chief Data Officer",
  "Chief Data Science Officer",
  "Chief Design Officer",
  "Chief DevOps Officer",
  "Chief Engineering Officer",
  "Chief Executive Officer",
  "Chief Finance Officer",
  "Chief Financial Officer",
  "Chief Human Resources Officer",
  "Chief Information Officer",
  "Chief Legal Officer",
  "Chief Marketing Officer",
  "Chief Operating Officer",
  "Chief Operations Officer",
  "Chief People Officer",
  "Chief Product Officer",
  "Chief Revenue Officer",
  "Chief Sales Officer",
  "Chief Security Officer",
  "Chief Strategy Officer",
  "Chief Technology Officer",
  "Civil Engineer",
  "Clinical Research Coordinator",
  "Cloud Architect",
  "Cloud Engineer",
  "Compliance Officer",
  "Construction Project Manager",
  "Content Marketing Manager",
  "Content Writer",
  "Controller",
  "Copywriter",
  "Corporate Development Manager",
  "Creative Director",
  "Credit Analyst",
  "Customer Success Manager",
  "Customer Support Specialist",
  "Cybersecurity Analyst",
  "Data Engineer",
  "Data Science Manager",
  "Data Scientist",
  "Database Administrator",
  "Demand Generation Manager",
  "Design Manager",
  "DevOps Engineer",
  "DevOps Manager",
  "Digital Marketing Manager",
  "Director of Customer Success",
  "Director of Data Science",
  "Director of Design",
  "Director of DevOps",
  "Director of Engineering",
  "Director of Finance",
  "Director of Human Resources",
  "Director of Legal",
  "Director of Marketing",
  "Director of Operations",
  "Director of Product",
  "Director of Sales",
  "Economist",
  "Electrical Engineer",
  "Engineering Manager",
  "Enterprise Account Executive",
  "Environmental Engineer",
  "Equity Research Analyst",
  "Event Manager",
  "Executive Assistant",
  "Executive Vice President of Customer Success",
  "Executive Vice President of Data Science",
  "Executive Vice President of Design",
  "Executive Vice President of DevOps",
  "Executive Vice President of Engineering",
  "Executive Vice President of Finance",
  "Executive Vice President of Human Resources",
  "Executive Vice President of Legal",
  "Executive Vice President of Marketing",
  "Executive Vice President of Operations",
  "Executive Vice President of Product",
  "Executive Vice President of Sales",
  "Executive VP of Customer Success",
  "Executive VP of Data Science",
  "Executive VP of Design",
  "Executive VP of DevOps",
  "Executive VP of Engineering",
  "Executive VP of Finance",
  "Executive VP of Human Resources",
  "Executive VP of Legal",
  "Executive VP of Marketing",
  "Executive VP of Operations",
  "Executive VP of Product",
  "Executive VP of Sales",
  "Facilities Manager",
  "Field Engineer",
  "Finance Director",
  "Finance Manager",
  "Financial Analyst",
  "FP&A Analyst",
  "Front End Developer",
  "Full Stack Developer",
  "General Manager",
  "Graphic Designer",
  "Growth Marketing Manager",
  "Head of Customer Success",
  "Head of Data Science",
  "Head of Design",
  "Head of DevOps",
  "Head of Engineering",
  "Head of Finance",
  "Head of Human Resources",
  "Head of Legal",
  "Head of Marketing",
  "Head of Operations",
  "Head of Product",
  "Head of Sales",
  "Healthcare Administrator",
  "HR Director",
  "HR Manager",
  "Human Resources Manager",
  "Implementation Specialist",
  "Instructional Designer",
  "Investment Banking Analyst",
  "iOS Developer",
  "IT Manager",
  "IT Support Specialist",
  "Java Developer",
  "Junior Account Executive",
  "Junior Account Manager",
  "Junior AI Engineer",
  "Junior Android Developer",
  "Junior Automation Engineer",
  "Junior Back End Developer",
  "Junior Brand Manager",
  "Junior Business Analyst",
  "Junior Business Intelligence Analyst",
  "Junior Cloud Architect",
  "Junior Cloud Engineer",
  "Junior Compliance Officer",
  "Junior Content Marketing Manager",
  "Junior Content Writer",
  "Junior Controller",
  "Junior Copywriter",
  "Junior Creative Director",
  "Junior Customer Success",
  "Junior Customer Success Analyst",
  "Junior Customer Success Associate",
  "Junior Customer Success Manager",
  "Junior Customer Success Specialist",
  "Junior Customer Support Specialist",
  "Junior Cybersecurity Analyst",
  "Junior Data Engineer",
  "Junior Data Science",
  "Junior Data Science Analyst",
  "Junior Data Science Associate",
  "Junior Data Science Engineer",
  "Junior Data Science Specialist",
  "Junior Data Scientist",
  "Junior Database Administrator",
  "Junior Design",
  "Junior Design Analyst",
  "Junior Design Associate",
  "Junior Design Specialist",
  "Junior DevOps",
  "Junior DevOps Analyst",
  "Junior DevOps Associate",
  "Junior DevOps Engineer",
  "Junior DevOps Specialist",
  "Junior Digital Marketing Manager",
  "Junior Engineering",
  "Junior Engineering Analyst",
  "Junior Engineering Associate",
  "Junior Engineering Engineer",
  "Junior Engineering Specialist",
  "Junior Event Manager",
  "Junior Executive Assistant",
  "Junior Finance",
  "Junior Finance Analyst",
  "Junior Finance Associate",
  "Junior Finance Specialist",
  "Junior Financial Analyst",
  "Junior Front End Developer",
  "Junior Full Stack Developer",
  "Junior Graphic Designer",
  "Junior HR Manager",
  "Junior Human Resources",
  "Junior Human Resources Analyst",
  "Junior Human Resources Associate",
  "Junior Human Resources Specialist",
  "Junior Investment Banking Analyst",
  "Junior iOS Developer",
  "Junior Legal",
  "Junior Legal Analyst",
  "Junior Legal Associate",
  "Junior Legal Counsel",
  "Junior Legal Specialist",
  "Junior Logistics Manager",
  "Junior Machine Learning Engineer",
  "Junior Marketing",
  "Junior Marketing Analyst",
  "Junior Marketing Associate",
  "Junior Marketing Manager",
  "Junior Marketing Specialist",
  "Junior Mobile Developer",
  "Junior Network Engineer",
  "Junior Operations",
  "Junior Operations Analyst",
  "Junior Operations Associate",
  "Junior Operations Manager",
  "Junior Operations Specialist",
  "Junior Paralegal",
  "Junior Product",
  "Junior Product Analyst",
  "Junior Product Associate",
  "Junior Product Designer",
  "Junior Product Manager",
  "Junior Product Marketing Manager",
  "Junior Product Specialist",
  "Junior Program Manager",
  "Junior Project Manager",
  "Junior QA Engineer",
  "Junior Quality Assurance Engineer",
  "Junior Recruiter",
  "Junior Research Scientist",
  "Junior Sales",
  "Junior Sales Analyst",
  "Junior Sales Associate",
  "Junior Sales Development Representative",
  "Junior Sales Engineer",
  "Junior Sales Specialist",
  "Junior Scrum Master",
  "Junior Security Engineer",
  "Junior SEO Specialist",
  "Junior Site Reliability Engineer",
  "Junior Social Media Manager",
  "Junior Software Architect",
  "Junior Software Engineer",
  "Junior Solutions Architect",
  "Junior Supply Chain Manager",
  "Junior Systems Administrator",
  "Junior Tax Accountant",
  "Junior Technical Program Manager",
  "Junior Technical Writer",
  "Junior UI Designer",
  "Junior UX Designer",
  "Junior UX Researcher",
  "Junior Web Developer",
  "Lead Account Executive",
  "Lead Account Manager",
  "Lead AI Engineer",
  "Lead Android Developer",
  "Lead Automation Engineer",
  "Lead Back End Developer",
  "Lead Brand Manager",
  "Lead Business Analyst",
  "Lead Business Intelligence Analyst",
  "Lead Cloud Architect",
  "Lead Cloud Engineer",
  "Lead Compliance Officer",
  "Lead Content Marketing Manager",
  "Lead Content Writer",
  "Lead Controller",
  "Lead Copywriter",
  "Lead Creative Director",
  "Lead Customer Success",
  "Lead Customer Success Analyst",
  "Lead Customer Success Associate",
  "Lead Customer Success Manager",
  "Lead Customer Success Specialist",
  "Lead Customer Support Specialist",
  "Lead Cybersecurity Analyst",
  "Lead Data Engineer",
  "Lead Data Science",
  "Lead Data Science Analyst",
  "Lead Data Science Associate",
  "Lead Data Science Engineer",
  "Lead Data Science Specialist",
  "Lead Data Scientist",
  "Lead Database Administrator",
  "Lead Design",
  "Lead Design Analyst",
  "Lead Design Associate",
  "Lead Design Specialist",
  "Lead DevOps",
  "Lead DevOps Analyst",
  "Lead DevOps Associate",
  "Lead DevOps Engineer",
  "Lead DevOps Specialist",
  "Lead Digital Marketing Manager",
  "Lead Engineering",
  "Lead Engineering Analyst",
  "Lead Engineering Associate",
  "Lead Engineering Engineer",
  "Lead Engineering Specialist",
  "Lead Event Manager",
  "Lead Executive Assistant",
  "Lead Finance",
  "Lead Finance Analyst",
  "Lead Finance Associate",
  "Lead Finance Specialist",
  "Lead Financial Analyst",
  "Lead Front End Developer",
  "Lead Full Stack Developer",
  "Lead Graphic Designer",
  "Lead HR Manager",
  "Lead Human Resources",
  "Lead Human Resources Analyst",
  "Lead Human Resources Associate",
  "Lead Human Resources Specialist",
  "Lead Investment Banking Analyst",
  "Lead iOS Developer",
  "Lead Legal",
  "Lead Legal Analyst",
  "Lead Legal Associate",
  "Lead Legal Counsel",
  "Lead Legal Specialist",
  "Lead Logistics Manager",
  "Lead Machine Learning Engineer",
  "Lead Marketing",
  "Lead Marketing Analyst",
  "Lead Marketing Associate",
  "Lead Marketing Manager",
  "Lead Marketing Specialist",
  "Lead Mobile Developer",
  "Lead Network Engineer",
  "Lead Operations",
  "Lead Operations Analyst",
  "Lead Operations Associate",
  "Lead Operations Manager",
  "Lead Operations Specialist",
  "Lead Paralegal",
  "Lead Product",
  "Lead Product Analyst",
  "Lead Product Associate",
  "Lead Product Designer",
  "Lead Product Manager",
  "Lead Product Marketing Manager",
  "Lead Product Specialist",
  "Lead Program Manager",
  "Lead Project Manager",
  "Lead QA Engineer",
  "Lead Quality Assurance Engineer",
  "Lead Recruiter",
  "Lead Research Scientist",
  "Lead Sales",
  "Lead Sales Analyst",
  "Lead Sales Associate",
  "Lead Sales Development Representative",
  "Lead Sales Engineer",
  "Lead Sales Specialist",
  "Lead Scrum Master",
  "Lead Security Engineer",
  "Lead SEO Specialist",
  "Lead Site Reliability Engineer",
  "Lead Social Media Manager",
  "Lead Software Architect",
  "Lead Software Engineer",
  "Lead Solutions Architect",
  "Lead Supply Chain Manager",
  "Lead Systems Administrator",
  "Lead Tax Accountant",
  "Lead Technical Program Manager",
  "Lead Technical Writer",
  "Lead UI Designer",
  "Lead UX Designer",
  "Lead UX Researcher",
  "Lead Web Developer",
  "Learning and Development Manager",
  "Legal Counsel",
  "Legal Director",
  "Legal Manager",
  "Logistics Manager",
  "Machine Learning Engineer",
  "Management Consultant",
  "Manager, Customer Success",
  "Manager, Data Science",
  "Manager, Design",
  "Manager, DevOps",
  "Manager, Engineering",
  "Manager, Finance",
  "Manager, Human Resources",
  "Manager, Legal",
  "Manager, Marketing",
  "Manager, Operations",
  "Manager, Product",
  "Manager, Sales",
  "Managing Director",
  "Marketing Director",
  "Marketing Manager",
  "Mechanical Engineer",
  "Mergers and Acquisitions Analyst",
  "Mobile Developer",
  "Network Engineer",
  "Nurse Practitioner",
  "Office Manager",
  "Operations Director",
  "Operations Manager",
  "Paralegal",
  "Partnerships Manager",
  "Payroll Specialist",
  "Pharmacist",
  "Physical Therapist",
  "Physician Assistant",
  "Portfolio Manager",
  "Principal Account Executive",
  "Principal Account Manager",
  "Principal AI Engineer",
  "Principal Android Developer",
  "Principal Automation Engineer",
  "Principal Back End Developer",
  "Principal Brand Manager",
  "Principal Business Analyst",
  "Principal Business Intelligence Analyst",
  "Principal Cloud Architect",
  "Principal Cloud Engineer",
  "Principal Compliance Officer",
  "Principal Content Marketing Manager",
  "Principal Content Writer",
  "Principal Controller",
  "Principal Copywriter",
  "Principal Creative Director",
  "Principal Customer Success",
  "Principal Customer Success Analyst",
  "Principal Customer Success Associate",
  "Principal Customer Success Manager",
  "Principal Customer Success Specialist",
  "Principal Customer Support Specialist",
  "Principal Cybersecurity Analyst",
  "Principal Data Engineer",
  "Principal Data Science",
  "Principal Data Science Analyst",
  "Principal Data Science Associate",
  "Principal Data Science Engineer",
  "Principal Data Science Specialist",
  "Principal Data Scientist",
  "Principal Database Administrator",
  "Principal Design",
  "Principal Design Analyst",
  "Principal Design Associate",
  "Principal Design Specialist",
  "Principal DevOps",
  "Principal DevOps Analyst",
  "Principal DevOps Associate",
  "Principal DevOps Engineer",
  "Principal DevOps Specialist",
  "Principal Digital Marketing Manager",
  "Principal Engineering",
  "Principal Engineering Analyst",
  "Principal Engineering Associate",
  "Principal Engineering Engineer",
  "Principal Engineering Specialist",
  "Principal Event Manager",
  "Principal Executive Assistant",
  "Principal Finance",
  "Principal Finance Analyst",
  "Principal Finance Associate",
  "Principal Finance Specialist",
  "Principal Financial Analyst",
  "Principal Front End Developer",
  "Principal Full Stack Developer",
  "Principal Graphic Designer",
  "Principal HR Manager",
  "Principal Human Resources",
  "Principal Human Resources Analyst",
  "Principal Human Resources Associate",
  "Principal Human Resources Specialist",
  "Principal Investment Banking Analyst",
  "Principal iOS Developer",
  "Principal Legal",
  "Principal Legal Analyst",
  "Principal Legal Associate",
  "Principal Legal Counsel",
  "Principal Legal Specialist",
  "Principal Logistics Manager",
  "Principal Machine Learning Engineer",
  "Principal Marketing",
  "Principal Marketing Analyst",
  "Principal Marketing Associate",
  "Principal Marketing Manager",
  "Principal Marketing Specialist",
  "Principal Mobile Developer",
  "Principal Network Engineer",
  "Principal Operations",
  "Principal Operations Analyst",
  "Principal Operations Associate",
  "Principal Operations Manager",
  "Principal Operations Specialist",
  "Principal Paralegal",
  "Principal Product",
  "Principal Product Analyst",
  "Principal Product Associate",
  "Principal Product Designer",
  "Principal Product Manager",
  "Principal Product Marketing Manager",
  "Principal Product Specialist",
  "Principal Program Manager",
  "Principal Project Manager",
  "Principal QA Engineer",
  "Principal Quality Assurance Engineer",
  "Principal Recruiter",
  "Principal Research Scientist",
  "Principal Sales",
  "Principal Sales Analyst",
  "Principal Sales Associate",
  "Principal Sales Development Representative",
  "Principal Sales Engineer",
  "Principal Sales Specialist",
  "Principal Scrum Master",
  "Principal Security Engineer",
  "Principal SEO Specialist",
  "Principal Site Reliability Engineer",
  "Principal Social Media Manager",
  "Principal Software Architect",
  "Principal Software Engineer",
  "Principal Solutions Architect",
  "Principal Supply Chain Manager",
  "Principal Systems Administrator",
  "Principal Tax Accountant",
  "Principal Technical Program Manager",
  "Principal Technical Writer",
  "Principal UI Designer",
  "Principal UX Designer",
  "Principal UX Researcher",
  "Principal Web Developer",
  "Procurement Manager",
  "Product Designer",
  "Product Manager",
  "Product Marketing Manager",
  "Program Manager",
  "Project Manager",
  "QA Engineer",
  "Quality Assurance Engineer",
  "Recruiter",
  "Registered Nurse",
  "Research Scientist",
  "Revenue Operations Manager",
  "Risk Analyst",
  "Sales Development Representative",
  "Sales Director",
  "Sales Engineer",
  "Sales Manager",
  "Scrum Master",
  "Security Engineer",
  "Senior Account Executive",
  "Senior Account Manager",
  "Senior AI Engineer",
  "Senior Android Developer",
  "Senior Automation Engineer",
  "Senior Back End Developer",
  "Senior Brand Manager",
  "Senior Business Analyst",
  "Senior Business Intelligence Analyst",
  "Senior Cloud Architect",
  "Senior Cloud Engineer",
  "Senior Compliance Officer",
  "Senior Content Marketing Manager",
  "Senior Content Writer",
  "Senior Controller",
  "Senior Copywriter",
  "Senior Creative Director",
  "Senior Customer Success",
  "Senior Customer Success Analyst",
  "Senior Customer Success Associate",
  "Senior Customer Success Manager",
  "Senior Customer Success Specialist",
  "Senior Customer Support Specialist",
  "Senior Cybersecurity Analyst",
  "Senior Data Engineer",
  "Senior Data Science",
  "Senior Data Science Analyst",
  "Senior Data Science Associate",
  "Senior Data Science Engineer",
  "Senior Data Science Manager",
  "Senior Data Science Specialist",
  "Senior Data Scientist",
  "Senior Database Administrator",
  "Senior Design",
  "Senior Design Analyst",
  "Senior Design Associate",
  "Senior Design Manager",
  "Senior Design Specialist",
  "Senior DevOps",
  "Senior DevOps Analyst",
  "Senior DevOps Associate",
  "Senior DevOps Engineer",
  "Senior DevOps Manager",
  "Senior DevOps Specialist",
  "Senior Digital Marketing Manager",
  "Senior Director of Customer Success",
  "Senior Director of Data Science",
  "Senior Director of Design",
  "Senior Director of DevOps",
  "Senior Director of Engineering",
  "Senior Director of Finance",
  "Senior Director of Human Resources",
  "Senior Director of Legal",
  "Senior Director of Marketing",
  "Senior Director of Operations",
  "Senior Director of Product",
  "Senior Director of Sales",
  "Senior Engineering",
  "Senior Engineering Analyst",
  "Senior Engineering Associate",
  "Senior Engineering Engineer",
  "Senior Engineering Manager",
  "Senior Engineering Specialist",
  "Senior Event Manager",
  "Senior Executive Assistant",
  "Senior Finance",
  "Senior Finance Analyst",
  "Senior Finance Associate",
  "Senior Finance Manager",
  "Senior Finance Specialist",
  "Senior Financial Analyst",
  "Senior Front End Developer",
  "Senior Full Stack Developer",
  "Senior Graphic Designer",
  "Senior HR Manager",
  "Senior Human Resources",
  "Senior Human Resources Analyst",
  "Senior Human Resources Associate",
  "Senior Human Resources Manager",
  "Senior Human Resources Specialist",
  "Senior Investment Banking Analyst",
  "Senior iOS Developer",
  "Senior Legal",
  "Senior Legal Analyst",
  "Senior Legal Associate",
  "Senior Legal Counsel",
  "Senior Legal Manager",
  "Senior Legal Specialist",
  "Senior Logistics Manager",
  "Senior Machine Learning Engineer",
  "Senior Manager, Customer Success",
  "Senior Manager, Data Science",
  "Senior Manager, Design",
  "Senior Manager, DevOps",
  "Senior Manager, Engineering",
  "Senior Manager, Finance",
  "Senior Manager, Human Resources",
  "Senior Manager, Legal",
  "Senior Manager, Marketing",
  "Senior Manager, Operations",
  "Senior Manager, Product",
  "Senior Manager, Sales",
  "Senior Marketing",
  "Senior Marketing Analyst",
  "Senior Marketing Associate",
  "Senior Marketing Manager",
  "Senior Marketing Specialist",
  "Senior Mobile Developer",
  "Senior Network Engineer",
  "Senior Operations",
  "Senior Operations Analyst",
  "Senior Operations Associate",
  "Senior Operations Manager",
  "Senior Operations Specialist",
  "Senior Paralegal",
  "Senior Product",
  "Senior Product Analyst",
  "Senior Product Associate",
  "Senior Product Designer",
  "Senior Product Manager",
  "Senior Product Marketing Manager",
  "Senior Product Specialist",
  "Senior Program Manager",
  "Senior Project Manager",
  "Senior QA Engineer",
  "Senior Quality Assurance Engineer",
  "Senior Recruiter",
  "Senior Research Scientist",
  "Senior Sales",
  "Senior Sales Analyst",
  "Senior Sales Associate",
  "Senior Sales Development Representative",
  "Senior Sales Engineer",
  "Senior Sales Manager",
  "Senior Sales Specialist",
  "Senior Scrum Master",
  "Senior Security Engineer",
  "Senior SEO Specialist",
  "Senior Site Reliability Engineer",
  "Senior Social Media Manager",
  "Senior Software Architect",
  "Senior Software Engineer",
  "Senior Solutions Architect",
  "Senior Supply Chain Manager",
  "Senior Systems Administrator",
  "Senior Tax Accountant",
  "Senior Technical Program Manager",
  "Senior Technical Writer",
  "Senior UI Designer",
  "Senior UX Designer",
  "Senior UX Researcher",
  "Senior Web Developer",
  "SEO Specialist",
  "Site Reliability Engineer",
  "Social Media Manager",
  "Software Architect",
  "Software Engineer",
  "Solutions Architect",
  "Staff Account Executive",
  "Staff Account Manager",
  "Staff AI Engineer",
  "Staff Android Developer",
  "Staff Automation Engineer",
  "Staff Back End Developer",
  "Staff Brand Manager",
  "Staff Business Analyst",
  "Staff Business Intelligence Analyst",
  "Staff Cloud Architect",
  "Staff Cloud Engineer",
  "Staff Compliance Officer",
  "Staff Content Marketing Manager",
  "Staff Content Writer",
  "Staff Controller",
  "Staff Copywriter",
  "Staff Creative Director",
  "Staff Customer Success Manager",
  "Staff Customer Support Specialist",
  "Staff Cybersecurity Analyst",
  "Staff Data Engineer",
  "Staff Data Scientist",
  "Staff Database Administrator",
  "Staff DevOps Engineer",
  "Staff Digital Marketing Manager",
  "Staff Event Manager",
  "Staff Executive Assistant",
  "Staff Financial Analyst",
  "Staff Front End Developer",
  "Staff Full Stack Developer",
  "Staff Graphic Designer",
  "Staff HR Manager",
  "Staff Investment Banking Analyst",
  "Staff iOS Developer",
  "Staff Legal Counsel",
  "Staff Logistics Manager",
  "Staff Machine Learning Engineer",
  "Staff Marketing Manager",
  "Staff Mobile Developer",
  "Staff Network Engineer",
  "Staff Operations Manager",
  "Staff Paralegal",
  "Staff Product Designer",
  "Staff Product Manager",
  "Staff Product Marketing Manager",
  "Staff Program Manager",
  "Staff Project Manager",
  "Staff QA Engineer",
  "Staff Quality Assurance Engineer",
  "Staff Recruiter",
  "Staff Research Scientist",
  "Staff Sales Development Representative",
  "Staff Sales Engineer",
  "Staff Scrum Master",
  "Staff Security Engineer",
  "Staff SEO Specialist",
  "Staff Site Reliability Engineer",
  "Staff Social Media Manager",
  "Staff Software Architect",
  "Staff Software Engineer",
  "Staff Solutions Architect",
  "Staff Supply Chain Manager",
  "Staff Systems Administrator",
  "Staff Tax Accountant",
  "Staff Technical Program Manager",
  "Staff Technical Writer",
  "Staff UI Designer",
  "Staff UX Designer",
  "Staff UX Researcher",
  "Staff Web Developer",
  "Strategic Account Manager",
  "Strategy Consultant",
  "Supply Chain Manager",
  "Systems Administrator",
  "Talent Acquisition Specialist",
  "Tax Accountant",
  "Technical Lead",
  "Technical Program Manager",
  "Technical Writer",
  "UI Designer",
  "UX Designer",
  "UX Researcher",
  "Vendor Manager",
  "Vice President of Customer Success",
  "Vice President of Data Science",
  "Vice President of Design",
  "Vice President of DevOps",
  "Vice President of Engineering",
  "Vice President of Finance",
  "Vice President of Human Resources",
  "Vice President of Legal",
  "Vice President of Marketing",
  "Vice President of Operations",
  "Vice President of Product",
  "Vice President of Sales",
  "VP of Customer Success",
  "VP of Data Science",
  "VP of Design",
  "VP of DevOps",
  "VP of Engineering",
  "VP of Finance",
  "VP of Human Resources",
  "VP of Legal",
  "VP of Marketing",
  "VP of Operations",
  "VP of Product",
  "VP of Sales",
  "Web Developer",
] as const;

export type PopularRole = (typeof POPULAR_ROLES)[number];

/** Score how well `text` matches `query` (higher is better; -1 = no match). */
export function fuzzyMatchScore(text: string, query: string): number {
  const haystack = text.toLowerCase();
  const needle = query.trim().toLowerCase();
  if (!needle) return 0;
  if (haystack === needle) return 1000;
  if (haystack.startsWith(needle)) {
    return 900 + (needle.length / haystack.length) * 50;
  }

  const words = haystack.split(/[\s/]+/).filter(Boolean);
  const queryTokens = needle.split(/\s+/).filter(Boolean);
  let tokenScore = 0;

  for (const token of queryTokens) {
    let matched = false;
    for (const word of words) {
      if (word.startsWith(token)) {
        tokenScore += 300;
        matched = true;
        break;
      }
      if (word.includes(token)) {
        tokenScore += 150;
        matched = true;
        break;
      }
    }
    if (!matched && haystack.includes(token)) {
      tokenScore += 80;
      matched = true;
    }
    if (!matched) return -1;
  }

  let needleIndex = 0;
  for (let i = 0; i < haystack.length && needleIndex < needle.length; i++) {
    if (haystack[i] === needle[needleIndex]) needleIndex++;
  }
  if (needleIndex < needle.length) return -1;

  return 100 + tokenScore;
}

export function isExactPopularRole(input: string): boolean {
  const trimmed = input.trim().toLowerCase();
  if (!trimmed) return false;
  return POPULAR_ROLES.some((role) => role.toLowerCase() === trimmed);
}

/** Fuzzy-ranked role suggestions for the Identity combobox. */
export function fuzzySearchPopularRoles(
  query: string,
  limit = 8,
): PopularRole[] {
  const trimmed = query.trim();
  if (!trimmed) return POPULAR_ROLES.slice(0, limit) as PopularRole[];

  return [...POPULAR_ROLES]
    .map((role) => ({ role, score: fuzzyMatchScore(role, trimmed) }))
    .filter((entry) => entry.score >= 0)
    .sort(
      (a, b) => b.score - a.score || a.role.localeCompare(b.role),
    )
    .slice(0, limit)
    .map((entry) => entry.role);
}

/** @deprecated Use {@link fuzzySearchPopularRoles} */
export function filterPopularRoles(query: string): PopularRole[] {
  return fuzzySearchPopularRoles(query, POPULAR_ROLES.length);
}
