/** Static dictionary for professional skills autocomplete and tagging. */
import { fuzzyMatchScore } from "@/src/lib/constants/roles";

export const MASTER_SKILLS = [
  "2D Animation",
  "3D Animation",
  "3D Modeling",
  "A/B Testing",
  "ABAP",
  "ABAP Programming",
  "Account Management",
  "Accountability",
  "Accounts Payable",
  "Accounts Receivable",
  "Active Directory",
  "Active Listening",
  "Ada",
  "ADA Compliance",
  "Ada Programming",
  "Adaptability",
  "Adobe After Effects",
  "Adobe Audition",
  "Adobe Creative Suite",
  "Adobe Experience Manager",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Lightroom",
  "Adobe Photoshop",
  "Adobe Premiere Pro",
  "Adobe XD",
  "Advanced API",
  "Advanced Application",
  "Advanced Backend",
  "Advanced Cloud",
  "Advanced Data",
  "Advanced Database",
  "Advanced DevOps",
  "Advanced Frontend",
  "Advanced Infrastructure",
  "Advanced Machine Learning",
  "Advanced Mobile",
  "Advanced Network",
  "Advanced Platform",
  "Advanced Security",
  "Advanced Software",
  "Advanced System",
  "Advanced Web",
  "Aerospace Audit",
  "Aerospace Compliance",
  "Aerospace Consulting",
  "Aerospace Engineering",
  "Aerospace Management",
  "Aerospace Marketing",
  "Aerospace Operations",
  "Aerospace Planning",
  "Aerospace Regulation",
  "Aerospace Risk Management",
  "Aerospace Sales",
  "Aerospace Standards",
  "Aerospace Strategy",
  "After Effects",
  "Agile",
  "Agile Coaching",
  "Agile Project Management",
  "Agile Software Development",
  "Airflow",
  "Amazon DynamoDB",
  "Amazon DynamoDB Administration",
  "Amazon RDS",
  "Amazon S3",
  "Analytical Thinking",
  "Android Development",
  "Angular",
  "Angular Development",
  "Animation",
  "Annual Planning",
  "Ansible",
  "Anti-Money Laundering",
  "Apache Airflow",
  "Apache Cassandra",
  "Apache Cassandra Administration",
  "Apache Hadoop",
  "Apache Kafka",
  "Apache Spark",
  "API Architecture",
  "API Automation",
  "API Design",
  "API Development",
  "API Engineering",
  "API Gateway",
  "API Integration",
  "API Monitoring",
  "API Operations",
  "API Optimization",
  "API Platform Engineering",
  "API Security",
  "API Troubleshooting",
  "App Store Optimization",
  "Application Architecture",
  "Application Automation",
  "Application Engineering",
  "Application Integration",
  "Application Monitoring",
  "Application Operations",
  "Application Optimization",
  "Application Performance Monitoring",
  "Application Platform Engineering",
  "Application Security",
  "Application Troubleshooting",
  "Applied API",
  "Applied Application",
  "Applied Backend",
  "Applied Cloud",
  "Applied Data",
  "Applied Database",
  "Applied DevOps",
  "Applied Frontend",
  "Applied Infrastructure",
  "Applied Machine Learning",
  "Applied Mobile",
  "Applied Network",
  "Applied Platform",
  "Applied Security",
  "Applied Software",
  "Applied System",
  "Applied Web",
  "ArcGIS",
  "Architectural Design",
  "ARM Templates",
  "Art Direction",
  "AS9100",
  "ASP.NET",
  "ASP.NET Core",
  "ASP.NET Core Development",
  "Assembly",
  "Assembly Language",
  "Assembly Programming",
  "Asset Management",
  "Attention to Detail",
  "Audio Editing",
  "Audio Mixing",
  "Audio Production",
  "Audit Management",
  "AutoCAD",
  "AutoML",
  "Automotive Audit",
  "Automotive Compliance",
  "Automotive Consulting",
  "Automotive Engineering",
  "Automotive Management",
  "Automotive Marketing",
  "Automotive Operations",
  "Automotive Planning",
  "Automotive Regulation",
  "Automotive Risk Management",
  "Automotive Sales",
  "Automotive Standards",
  "Automotive Strategy",
  "Aviation Safety",
  "AWS",
  "AWS CloudFormation",
  "AWS EC2",
  "AWS ECS",
  "AWS EKS",
  "AWS IAM",
  "AWS Lambda",
  "AWS RDS",
  "AWS S3",
  "AWS SageMaker",
  "Azure",
  "Azure Active Directory",
  "Azure Blob Storage",
  "Azure Cosmos DB",
  "Azure Data Factory",
  "Azure DevOps",
  "Azure Functions",
  "Azure Kubernetes Service",
  "Azure Monitor",
  "Azure SQL",
  "Azure Virtual Machines",
  "B2B Marketing",
  "B2B Sales",
  "B2C Marketing",
  "Backend Architecture",
  "Backend Automation",
  "Backend Development",
  "Backend Engineering",
  "Backend Integration",
  "Backend Monitoring",
  "Backend Operations",
  "Backend Optimization",
  "Backend Platform Engineering",
  "Backend Troubleshooting",
  "Balance Sheet Analysis",
  "Banking Audit",
  "Banking Compliance",
  "Banking Consulting",
  "Banking Engineering",
  "Banking Management",
  "Banking Marketing",
  "Banking Operations",
  "Banking Planning",
  "Banking Regulation",
  "Banking Risk Management",
  "Banking Sales",
  "Banking Standards",
  "Banking Strategy",
  "Bankruptcy Law",
  "Bash",
  "Bash Programming",
  "Bash Scripting",
  "Behavioral Health",
  "Benchmarking",
  "Big Data",
  "BigQuery",
  "Bioinformatics",
  "Biomedical Engineering",
  "Biostatistics",
  "Biotech Audit",
  "Biotech Compliance",
  "Biotech Consulting",
  "Biotech Engineering",
  "Biotech Management",
  "Biotech Marketing",
  "Biotech Operations",
  "Biotech Planning",
  "Biotech Regulation",
  "Biotech Risk Management",
  "Biotech Sales",
  "Biotech Standards",
  "Biotech Strategy",
  "Bitbucket",
  "Blockchain",
  "Blockchain Compliance",
  "Board Reporting",
  "Bootstrap",
  "Brand Art Direction",
  "Brand Copywriting",
  "Brand Design",
  "Brand Direction",
  "Brand Guidelines",
  "Brand Identity",
  "Brand Illustration",
  "Brand Management",
  "Brand Photography",
  "Brand Production",
  "Brand Storytelling",
  "Brand Strategy",
  "Brand Writing",
  "Broadcast Design",
  "Budget Forecasting",
  "Budget Management",
  "Budget Planning",
  "Building Codes",
  "Building Trust",
  "Business Analysis",
  "Business Case Development",
  "Business Continuity Planning",
  "Business Development",
  "Business Intelligence",
  "Business Model Innovation",
  "Business Operations",
  "Business Planning",
  "Business Process Improvement",
  "Business Process Management",
  "Business Process Reengineering",
  "Business Strategy",
  "Business Transformation",
  "Business Valuation",
  "C",
  "C Programming",
  "C#",
  "C# Programming",
  "C++",
  "C++ Programming",
  "Campaign Art Direction",
  "Campaign Copywriting",
  "Campaign Design",
  "Campaign Direction",
  "Campaign Illustration",
  "Campaign Photography",
  "Campaign Production",
  "Campaign Storytelling",
  "Campaign Strategy",
  "Campaign Writing",
  "Canva",
  "CAPA Management",
  "Capacity Planning",
  "Cardiology",
  "Cash Flow Analysis",
  "Cash Flow Management",
  "Change Management",
  "Channel Sales",
  "Chemical Engineering",
  "CI/CD",
  "Cinematography",
  "CircleCI",
  "Civil Engineering",
  "Client Collaboration",
  "Client Communication",
  "Client Decision Making",
  "Client Leadership",
  "Client Negotiation",
  "Client Problem Solving",
  "Client Relations",
  "Client Retention",
  "Client Time Management",
  "Clinical Data Management",
  "Clinical Research",
  "Clinical Trials",
  "Clojure",
  "Clojure Programming",
  "Cloud API",
  "Cloud Application",
  "Cloud Architecture",
  "Cloud Automation",
  "Cloud Backend",
  "Cloud Cloud",
  "Cloud Compliance",
  "Cloud Computing",
  "Cloud Data",
  "Cloud Database",
  "Cloud DevOps",
  "Cloud Engineering",
  "Cloud Frontend",
  "Cloud Infrastructure",
  "Cloud Integration",
  "Cloud Machine Learning",
  "Cloud Migration",
  "Cloud Mobile",
  "Cloud Monitoring",
  "Cloud Network",
  "Cloud Operations",
  "Cloud Optimization",
  "Cloud Platform",
  "Cloud Platform Engineering",
  "Cloud Security",
  "Cloud Software",
  "Cloud System",
  "Cloud Troubleshooting",
  "Cloud Web",
  "CloudFront",
  "CloudTrail",
  "CloudWatch",
  "Coaching",
  "COBOL",
  "COBOL Programming",
  "CockroachDB",
  "CockroachDB Administration",
  "Collaboration",
  "Color Correction",
  "Color Grading",
  "Color Theory",
  "Commercial Analytics",
  "Commercial Budgeting",
  "Commercial Compliance",
  "Commercial Consulting",
  "Commercial Development",
  "Commercial Enablement",
  "Commercial Excellence",
  "Commercial Governance",
  "Commercial Growth",
  "Commercial Insights",
  "Commercial Intelligence",
  "Commercial Management",
  "Commercial Operations",
  "Commercial Optimization",
  "Commercial Performance",
  "Commercial Planning",
  "Commercial Reporting",
  "Commercial Strategy",
  "Commercial Transformation",
  "Communication",
  "Competitive Analysis",
  "Compliance Management",
  "Composition",
  "Computer Vision",
  "Concept Art",
  "Conflict Resolution",
  "Confluence",
  "Construction Audit",
  "Construction Compliance",
  "Construction Consulting",
  "Construction Engineering",
  "Construction Management",
  "Construction Marketing",
  "Construction Operations",
  "Construction Planning",
  "Construction Regulation",
  "Construction Risk Management",
  "Construction Sales",
  "Construction Standards",
  "Construction Strategy",
  "Container Orchestration",
  "Containerization",
  "Content Art Direction",
  "Content Copywriting",
  "Content Creation",
  "Content Design",
  "Content Direction",
  "Content Illustration",
  "Content Photography",
  "Content Production",
  "Content Storytelling",
  "Content Strategy",
  "Content Writing",
  "Continuous Delivery",
  "Continuous Deployment",
  "Continuous Integration",
  "Contract Law",
  "Contract Management",
  "Contract Negotiation",
  "Copy Editing",
  "Copywriting",
  "Corporate Analytics",
  "Corporate Budgeting",
  "Corporate Compliance",
  "Corporate Consulting",
  "Corporate Development",
  "Corporate Enablement",
  "Corporate Excellence",
  "Corporate Finance",
  "Corporate Governance",
  "Corporate Growth",
  "Corporate Insights",
  "Corporate Intelligence",
  "Corporate Law",
  "Corporate Management",
  "Corporate Operations",
  "Corporate Optimization",
  "Corporate Performance",
  "Corporate Planning",
  "Corporate Reporting",
  "Corporate Strategy",
  "Corporate Transformation",
  "Cosmetic Chemistry",
  "Cost Accounting",
  "Cost Analysis",
  "Cost Control",
  "Cost Reduction",
  "CouchDB",
  "CouchDB Administration",
  "Creative Direction",
  "Creative Problem Solving",
  "Creative Writing",
  "Credit Risk Analysis",
  "Criminal Law",
  "Critical Thinking",
  "CRM",
  "Cross-Cultural Communication",
  "Cross-Functional Collaboration",
  "Cross-Functional Communication",
  "Cross-Functional Decision Making",
  "Cross-Functional Leadership",
  "Cross-Functional Negotiation",
  "Cross-Functional Problem Solving",
  "Cross-Functional Time Management",
  "Crystal",
  "Crystal Programming",
  "CSS",
  "CSS3",
  "Customer Acquisition",
  "Customer Analytics",
  "Customer Experience Management",
  "Customer Journey Mapping",
  "Customer Relationship Management",
  "Customer Retention",
  "Customer Segmentation",
  "Customer Success",
  "Customer Support Management",
  "Cyber Risk Management",
  "Cybersecurity",
  "Dart",
  "Dart Programming",
  "Data Architecture",
  "Data Automation",
  "Data Engineering",
  "Data Governance",
  "Data Integration",
  "Data Lakes",
  "Data Modeling",
  "Data Monitoring",
  "Data Operations",
  "Data Optimization",
  "Data Pipelines",
  "Data Platform Engineering",
  "Data Privacy",
  "Data Quality",
  "Data Science",
  "Data Structures",
  "Data Troubleshooting",
  "Data Visualization",
  "Data Warehousing",
  "Data-Driven Decision Making",
  "Database Administration",
  "Database Architecture",
  "Database Automation",
  "Database Design",
  "Database Engineering",
  "Database Integration",
  "Database Monitoring",
  "Database Operations",
  "Database Optimization",
  "Database Platform Engineering",
  "Database Troubleshooting",
  "Databricks",
  "Datadog",
  "dbt",
  "Decision Making",
  "Deep Learning",
  "Defensive Programming",
  "Delegation",
  "Demand Forecasting",
  "Demand Generation",
  "Demand Planning",
  "Dependability",
  "Dermatology",
  "Design Systems",
  "Design Thinking",
  "DevOps",
  "DevOps Architecture",
  "DevOps Automation",
  "DevOps Engineering",
  "DevOps Integration",
  "DevOps Monitoring",
  "DevOps Operations",
  "DevOps Optimization",
  "DevOps Platform Engineering",
  "DevOps Troubleshooting",
  "DevSecOps",
  "Differential Diagnosis",
  "Digital Art Direction",
  "Digital Copywriting",
  "Digital Design",
  "Digital Direction",
  "Digital Forensics",
  "Digital Illustration",
  "Digital Marketing",
  "Digital Painting",
  "Digital Photography",
  "Digital Production",
  "Digital Storytelling",
  "Digital Strategy",
  "Digital Transformation",
  "Digital Writing",
  "Diplomacy",
  "Direct Sales",
  "Distributed API",
  "Distributed Application",
  "Distributed Backend",
  "Distributed Cloud",
  "Distributed Data",
  "Distributed Database",
  "Distributed DevOps",
  "Distributed Frontend",
  "Distributed Infrastructure",
  "Distributed Machine Learning",
  "Distributed Mobile",
  "Distributed Network",
  "Distributed Platform",
  "Distributed Security",
  "Distributed Software",
  "Distributed System",
  "Distributed Web",
  "Django",
  "Django Development",
  "Docker",
  "Domain-Driven Design",
  "Due Diligence",
  "DynamoDB",
  "E-Commerce",
  "E-Commerce Strategy",
  "Editorial Art Direction",
  "Editorial Copywriting",
  "Editorial Design",
  "Editorial Direction",
  "Editorial Illustration",
  "Editorial Photography",
  "Editorial Production",
  "Editorial Storytelling",
  "Editorial Strategy",
  "Editorial Writing",
  "Education Audit",
  "Education Compliance",
  "Education Consulting",
  "Education Engineering",
  "Education Management",
  "Education Marketing",
  "Education Operations",
  "Education Planning",
  "Education Regulation",
  "Education Risk Management",
  "Education Sales",
  "Education Standards",
  "Education Strategy",
  "Elasticsearch",
  "Elasticsearch Administration",
  "Electrical Engineering",
  "Electron",
  "Elixir",
  "Elixir Programming",
  "Email Marketing",
  "Embedded Systems",
  "Emergency Medicine",
  "Emotional Intelligence",
  "Empathy",
  "Energy Audit",
  "Energy Compliance",
  "Energy Consulting",
  "Energy Engineering",
  "Energy Management",
  "Energy Marketing",
  "Energy Operations",
  "Energy Planning",
  "Energy Regulation",
  "Energy Risk Management",
  "Energy Sales",
  "Energy Standards",
  "Energy Strategy",
  "Enterprise Analytics",
  "Enterprise API",
  "Enterprise Application",
  "Enterprise Backend",
  "Enterprise Budgeting",
  "Enterprise Cloud",
  "Enterprise Compliance",
  "Enterprise Consulting",
  "Enterprise Data",
  "Enterprise Database",
  "Enterprise Development",
  "Enterprise DevOps",
  "Enterprise Enablement",
  "Enterprise Excellence",
  "Enterprise Frontend",
  "Enterprise Governance",
  "Enterprise Growth",
  "Enterprise Infrastructure",
  "Enterprise Insights",
  "Enterprise Intelligence",
  "Enterprise Machine Learning",
  "Enterprise Management",
  "Enterprise Mobile",
  "Enterprise Network",
  "Enterprise Operations",
  "Enterprise Optimization",
  "Enterprise Performance",
  "Enterprise Planning",
  "Enterprise Platform",
  "Enterprise Reporting",
  "Enterprise Sales",
  "Enterprise Security",
  "Enterprise Software",
  "Enterprise Strategy",
  "Enterprise System",
  "Enterprise Transformation",
  "Enterprise Web",
  "Entity Framework",
  "Entrepreneurship",
  "Environmental Compliance",
  "Environmental Design",
  "Environmental Engineering",
  "Epidemiology",
  "Erlang",
  "Erlang Programming",
  "ERP Implementation",
  "ETL",
  "Event Design",
  "Event Management",
  "Executive Collaboration",
  "Executive Communication",
  "Executive Decision Making",
  "Executive Leadership",
  "Executive Negotiation",
  "Executive Presence",
  "Executive Problem Solving",
  "Executive Reporting",
  "Executive Time Management",
  "Expense Management",
  "Experiential Art Direction",
  "Experiential Copywriting",
  "Experiential Design",
  "Experiential Direction",
  "Experiential Illustration",
  "Experiential Photography",
  "Experiential Production",
  "Experiential Storytelling",
  "Experiential Strategy",
  "Experiential Writing",
  "Express.js",
  "Express.js Development",
  "F#",
  "F# Programming",
  "Facilitation",
  "Family Law",
  "FastAPI",
  "FastAPI Development",
  "FDA Regulations",
  "Feature Flags",
  "Feedback Delivery",
  "Field Service Engineering",
  "Figma",
  "Figma Dev Mode",
  "Film Editing",
  "Film Production",
  "Finance Audit",
  "Finance Compliance",
  "Finance Consulting",
  "Finance Engineering",
  "Finance Management",
  "Finance Marketing",
  "Finance Operations",
  "Finance Planning",
  "Finance Regulation",
  "Finance Risk Management",
  "Finance Sales",
  "Finance Standards",
  "Finance Strategy",
  "Financial Accounting",
  "Financial Analysis",
  "Financial Forecasting",
  "Financial Management",
  "Financial Modeling",
  "Financial Planning",
  "Financial Regulation",
  "Financial Reporting",
  "Financial Strategy",
  "Fire Protection Engineering",
  "Firebase",
  "Flask",
  "Flask Development",
  "Flutter",
  "Flutter Development",
  "Food Safety",
  "Forecasting",
  "Forensic Accounting",
  "Forensic Analysis",
  "Fortran",
  "Fortran Programming",
  "Franchise Management",
  "Frontend Architecture",
  "Frontend Automation",
  "Frontend Development",
  "Frontend Engineering",
  "Frontend Integration",
  "Frontend Monitoring",
  "Frontend Operations",
  "Frontend Optimization",
  "Frontend Platform Engineering",
  "Frontend Troubleshooting",
  "Full Stack Development",
  "Functional Programming",
  "Fundraising",
  "Gap Analysis",
  "GCP",
  "GDPR Compliance",
  "General Ledger",
  "Geospatial Analysis",
  "Git",
  "GitHub",
  "GitHub Actions",
  "GitLab",
  "GitLab CI",
  "Global Analytics",
  "Global Budgeting",
  "Global Collaboration",
  "Global Communication",
  "Global Compliance",
  "Global Consulting",
  "Global Decision Making",
  "Global Development",
  "Global Enablement",
  "Global Excellence",
  "Global Governance",
  "Global Growth",
  "Global Insights",
  "Global Intelligence",
  "Global Leadership",
  "Global Management",
  "Global Negotiation",
  "Global Operations",
  "Global Optimization",
  "Global Performance",
  "Global Planning",
  "Global Problem Solving",
  "Global Reporting",
  "Global Strategy",
  "Global Time Management",
  "Global Transformation",
  "GMP Compliance",
  "Go",
  "Go Programming",
  "Go-To-Market Strategy",
  "Good Clinical Practice",
  "Google BigQuery",
  "Google Cloud Functions",
  "Google Cloud Platform",
  "Google Cloud Run",
  "Google Cloud Storage",
  "Google Compute Engine",
  "Google Kubernetes Engine",
  "Government Audit",
  "Government Compliance",
  "Government Consulting",
  "Government Engineering",
  "Government Management",
  "Government Marketing",
  "Government Operations",
  "Government Planning",
  "Government Regulation",
  "Government Risk Management",
  "Government Sales",
  "Government Standards",
  "Government Strategy",
  "Grafana",
  "Graphic Design",
  "GraphQL",
  "Groovy",
  "Groovy Programming",
  "Growth Hacking",
  "Growth Mindset",
  "Growth Strategy",
  "gRPC",
  "HACCP",
  "Hadoop",
  "HashiCorp Vault",
  "Haskell",
  "Haskell Programming",
  "Healthcare Administration",
  "Healthcare Audit",
  "Healthcare Compliance",
  "Healthcare Consulting",
  "Healthcare Engineering",
  "Healthcare Management",
  "Healthcare Marketing",
  "Healthcare Operations",
  "Healthcare Planning",
  "Healthcare Regulation",
  "Healthcare Risk Management",
  "Healthcare Sales",
  "Healthcare Standards",
  "Healthcare Strategy",
  "Helm",
  "HIPAA Compliance",
  "Hospital Operations",
  "Hospitality Audit",
  "Hospitality Compliance",
  "Hospitality Consulting",
  "Hospitality Engineering",
  "Hospitality Management",
  "Hospitality Marketing",
  "Hospitality Operations",
  "Hospitality Planning",
  "Hospitality Regulation",
  "Hospitality Risk Management",
  "Hospitality Sales",
  "Hospitality Standards",
  "Hospitality Strategy",
  "HR Analytics",
  "HR Business Partnering",
  "HR Compliance",
  "HR Operations",
  "HR Strategy",
  "HTML",
  "HTML5",
  "Hugging Face",
  "Human Factors Engineering",
  "IBM Db2",
  "IBM Db2 Administration",
  "Icon Design",
  "Identity and Access Management",
  "Illustration",
  "Immigration Law",
  "Inbound Marketing",
  "Income Statement Analysis",
  "Industrial Design",
  "Industrial Engineering",
  "Influence",
  "InfluxDB",
  "InfluxDB Administration",
  "Infographic Design",
  "Information Architecture",
  "Infrastructure Architecture",
  "Infrastructure as Code",
  "Infrastructure Automation",
  "Infrastructure Engineering",
  "Infrastructure Integration",
  "Infrastructure Monitoring",
  "Infrastructure Operations",
  "Infrastructure Optimization",
  "Infrastructure Platform Engineering",
  "Infrastructure Troubleshooting",
  "Initiative",
  "Inside Sales",
  "Insurance Audit",
  "Insurance Compliance",
  "Insurance Consulting",
  "Insurance Engineering",
  "Insurance Management",
  "Insurance Marketing",
  "Insurance Operations",
  "Insurance Planning",
  "Insurance Regulation",
  "Insurance Risk Management",
  "Insurance Sales",
  "Insurance Standards",
  "Insurance Strategy",
  "Integrity",
  "Intellectual Property Law",
  "Interaction Design",
  "Interactive Art Direction",
  "Interactive Copywriting",
  "Interactive Design",
  "Interactive Direction",
  "Interactive Illustration",
  "Interactive Photography",
  "Interactive Production",
  "Interactive Storytelling",
  "Interactive Strategy",
  "Interactive Writing",
  "Interior Design",
  "Internal Audit",
  "Internal Controls",
  "International Tax",
  "Interpersonal Skills",
  "Inventory Management",
  "Investment Analysis",
  "Investment Banking",
  "Investor Relations",
  "Invoice Processing",
  "iOS Development",
  "IoT",
  "ISO 13485",
  "ISO 14001",
  "ISO 27001",
  "ISO 9001",
  "IT Audit",
  "ITIL",
  "Java",
  "Java Programming",
  "JavaScript",
  "JavaScript Programming",
  "Jenkins",
  "Jest",
  "JIRA",
  "Journalism",
  "JSON",
  "Julia",
  "Julia Programming",
  "JUnit",
  "Kafka",
  "Kanban",
  "Keras",
  "Key Account Management",
  "Kotlin",
  "Kotlin Programming",
  "KPI Development",
  "Kubernetes",
  "Labor Law",
  "LangChain",
  "Laravel",
  "Laravel Development",
  "Layout Design",
  "Lead Generation",
  "Leadership",
  "Leadership Development",
  "Lean Management",
  "Lean Startup",
  "Legal Audit",
  "Legal Compliance",
  "Legal Consulting",
  "Legal Engineering",
  "Legal Management",
  "Legal Marketing",
  "Legal Operations",
  "Legal Planning",
  "Legal Regulation",
  "Legal Research",
  "Legal Risk Management",
  "Legal Sales",
  "Legal Standards",
  "Legal Strategy",
  "Legal Writing",
  "Linux Administration",
  "Litigation Support",
  "Load Balancing",
  "Logistics Audit",
  "Logistics Compliance",
  "Logistics Consulting",
  "Logistics Engineering",
  "Logistics Management",
  "Logistics Marketing",
  "Logistics Operations",
  "Logistics Planning",
  "Logistics Regulation",
  "Logistics Risk Management",
  "Logistics Sales",
  "Logistics Standards",
  "Logistics Strategy",
  "Logo Design",
  "Lua",
  "Lua Programming",
  "M&A Integration",
  "Machine Learning",
  "Machine Learning Architecture",
  "Machine Learning Automation",
  "Machine Learning Engineering",
  "Machine Learning Integration",
  "Machine Learning Monitoring",
  "Machine Learning Operations",
  "Machine Learning Optimization",
  "Machine Learning Platform Engineering",
  "Machine Learning Troubleshooting",
  "Management Accounting",
  "Management Consulting",
  "Manufacturing Audit",
  "Manufacturing Compliance",
  "Manufacturing Consulting",
  "Manufacturing Engineering",
  "Manufacturing Management",
  "Manufacturing Marketing",
  "Manufacturing Operations",
  "Manufacturing Planning",
  "Manufacturing Regulation",
  "Manufacturing Risk Management",
  "Manufacturing Sales",
  "Manufacturing Standards",
  "Manufacturing Strategy",
  "MariaDB",
  "MariaDB Administration",
  "Marine Engineering",
  "Market Analysis",
  "Market Entry Strategy",
  "Market Research",
  "Market Segmentation",
  "Marketing Analytics",
  "Marketing Art Direction",
  "Marketing Automation",
  "Marketing Communications",
  "Marketing Copywriting",
  "Marketing Design",
  "Marketing Direction",
  "Marketing Illustration",
  "Marketing Operations",
  "Marketing Photography",
  "Marketing Production",
  "Marketing Storytelling",
  "Marketing Strategy",
  "Marketing Writing",
  "MATLAB",
  "MATLAB Programming",
  "Mechanical Design",
  "Mechanical Engineering",
  "Media Audit",
  "Media Compliance",
  "Media Consulting",
  "Media Engineering",
  "Media Management",
  "Media Marketing",
  "Media Operations",
  "Media Planning",
  "Media Regulation",
  "Media Risk Management",
  "Media Sales",
  "Media Standards",
  "Media Strategy",
  "Medical Coding",
  "Medical Device Regulation",
  "Medical Writing",
  "Mentoring",
  "Merchandising",
  "Merger Integration",
  "Mergers and Acquisitions",
  "Metallurgy",
  "Metrics and KPIs",
  "Microbiology",
  "Microservices",
  "Microsoft SQL Server",
  "Microsoft SQL Server Administration",
  "Mining Engineering",
  "Mobile Architecture",
  "Mobile Automation",
  "Mobile Development",
  "Mobile Engineering",
  "Mobile Integration",
  "Mobile Monitoring",
  "Mobile Operations",
  "Mobile Optimization",
  "Mobile Platform Engineering",
  "Mobile Troubleshooting",
  "Modern API",
  "Modern Application",
  "Modern Backend",
  "Modern Cloud",
  "Modern Data",
  "Modern Database",
  "Modern DevOps",
  "Modern Frontend",
  "Modern Infrastructure",
  "Modern Machine Learning",
  "Modern Mobile",
  "Modern Network",
  "Modern Platform",
  "Modern Security",
  "Modern Software",
  "Modern System",
  "Modern Web",
  "MongoDB",
  "MongoDB Administration",
  "Motion Art Direction",
  "Motion Copywriting",
  "Motion Design",
  "Motion Direction",
  "Motion Graphics",
  "Motion Illustration",
  "Motion Photography",
  "Motion Production",
  "Motion Storytelling",
  "Motion Strategy",
  "Motion Writing",
  "Motivation",
  "Multimedia Production",
  "MySQL",
  "MySQL Administration",
  "Natural Language Processing",
  "Negotiation",
  "Negotiation Skills",
  "Neo4j",
  "Neo4j Administration",
  "Net Promoter Score",
  "Network Administration",
  "Network Architecture",
  "Network Automation",
  "Network Engineering",
  "Network Integration",
  "Network Monitoring",
  "Network Operations",
  "Network Optimization",
  "Network Platform Engineering",
  "Network Security",
  "Network Troubleshooting",
  "Networking",
  "New Relic",
  "Next.js",
  "Next.js Development",
  "Node.js",
  "Node.js Development",
  "Nonprofit Audit",
  "Nonprofit Compliance",
  "Nonprofit Consulting",
  "Nonprofit Engineering",
  "Nonprofit Management",
  "Nonprofit Marketing",
  "Nonprofit Operations",
  "Nonprofit Planning",
  "Nonprofit Regulation",
  "Nonprofit Risk Management",
  "Nonprofit Sales",
  "Nonprofit Standards",
  "Nonprofit Strategy",
  "NoSQL",
  "Notion",
  "Nursing Care",
  "Nuxt.js",
  "Nuxt.js Development",
  "OAuth",
  "Object-Oriented Programming",
  "Objective-C",
  "Objective-C Programming",
  "Observability",
  "OCaml",
  "OCaml Programming",
  "Occupational Health and Safety",
  "Occupational Therapy",
  "Oil and Gas Operations",
  "OKRs",
  "Oncology",
  "Open-Mindedness",
  "OpenAI API",
  "OpenShift",
  "OpenStack",
  "Operational Excellence",
  "Operations Management",
  "Operations Strategy",
  "Oracle Database",
  "Oracle Database Administration",
  "Order Management",
  "Organizational Design",
  "Organizational Development",
  "Organizational Skills",
  "ORM",
  "OSHA Compliance",
  "Outbound Sales",
  "P&L Management",
  "Packaging Art Direction",
  "Packaging Copywriting",
  "Packaging Design",
  "Packaging Direction",
  "Packaging Illustration",
  "Packaging Photography",
  "Packaging Production",
  "Packaging Storytelling",
  "Packaging Strategy",
  "Packaging Writing",
  "PagerDuty",
  "Pandas",
  "Partnership Development",
  "Partnership Management",
  "Patent Analysis",
  "Patience",
  "Patient Advocacy",
  "Patient Care",
  "Payroll Administration",
  "Pediatrics",
  "Penetration Testing",
  "Performance Management",
  "Performance Metrics",
  "Performance Optimization",
  "Perl",
  "Perl Programming",
  "Persuasion",
  "Pharmaceutical Audit",
  "Pharmaceutical Compliance",
  "Pharmaceutical Consulting",
  "Pharmaceutical Engineering",
  "Pharmaceutical Management",
  "Pharmaceutical Marketing",
  "Pharmaceutical Operations",
  "Pharmaceutical Planning",
  "Pharmaceutical Regulation",
  "Pharmaceutical Risk Management",
  "Pharmaceutical Sales",
  "Pharmaceutical Standards",
  "Pharmaceutical Strategy",
  "Pharmacovigilance",
  "Photo Retouching",
  "Photography",
  "PHP",
  "PHP Programming",
  "Physical Therapy",
  "Platform Architecture",
  "Platform Automation",
  "Platform Engineering",
  "Platform Integration",
  "Platform Monitoring",
  "Platform Operations",
  "Platform Optimization",
  "Platform Platform Engineering",
  "Platform Troubleshooting",
  "Podcast Production",
  "Portfolio Management",
  "PostgreSQL",
  "PostgreSQL Administration",
  "Postman",
  "Power BI",
  "Power Systems Engineering",
  "PowerShell",
  "PowerShell Programming",
  "Presentation Skills",
  "Pricing Strategy",
  "Print Design",
  "Prioritization",
  "Problem Solving",
  "Process Engineering",
  "Process Validation",
  "Procurement",
  "Product Art Direction",
  "Product Compliance",
  "Product Copywriting",
  "Product Design",
  "Product Direction",
  "Product Illustration",
  "Product Launch",
  "Product Lifecycle Management",
  "Product Management",
  "Product Marketing",
  "Product Photography",
  "Product Production",
  "Product Storytelling",
  "Product Strategy",
  "Product Writing",
  "Professionalism",
  "Profit and Loss Management",
  "Program Management",
  "Project Management",
  "Project Planning",
  "Project Portfolio Management",
  "Prometheus",
  "Prompt Engineering",
  "Proposal Writing",
  "Prototyping",
  "Public Health",
  "Public Relations",
  "Public Speaking",
  "Purchasing",
  "PySpark",
  "Python",
  "Python Programming",
  "PyTorch",
  "Quality Assurance Management",
  "Quality Engineering",
  "Quarterly Business Reviews",
  "Quota Attainment",
  "R",
  "R Programming",
  "RabbitMQ",
  "Radiology",
  "React",
  "React Development",
  "React Native",
  "React Native Development",
  "Real Estate Audit",
  "Real Estate Compliance",
  "Real Estate Consulting",
  "Real Estate Engineering",
  "Real Estate Law",
  "Real Estate Management",
  "Real Estate Marketing",
  "Real Estate Operations",
  "Real Estate Planning",
  "Real Estate Regulation",
  "Real Estate Risk Management",
  "Real Estate Sales",
  "Real Estate Standards",
  "Real Estate Strategy",
  "Real-Time API",
  "Real-Time Application",
  "Real-Time Backend",
  "Real-Time Cloud",
  "Real-Time Data",
  "Real-Time Database",
  "Real-Time DevOps",
  "Real-Time Frontend",
  "Real-Time Infrastructure",
  "Real-Time Machine Learning",
  "Real-Time Mobile",
  "Real-Time Network",
  "Real-Time Platform",
  "Real-Time Security",
  "Real-Time Software",
  "Real-Time System",
  "Real-Time Web",
  "Redis",
  "Redis Administration",
  "Redux",
  "Regional Analytics",
  "Regional Budgeting",
  "Regional Compliance",
  "Regional Consulting",
  "Regional Development",
  "Regional Enablement",
  "Regional Excellence",
  "Regional Governance",
  "Regional Growth",
  "Regional Insights",
  "Regional Intelligence",
  "Regional Management",
  "Regional Operations",
  "Regional Optimization",
  "Regional Performance",
  "Regional Planning",
  "Regional Reporting",
  "Regional Strategy",
  "Regional Transformation",
  "Regression Testing",
  "Regulatory Affairs",
  "Regulatory Compliance",
  "Relationship Building",
  "Reliability",
  "Remote Collaboration",
  "Remote Communication",
  "Remote Decision Making",
  "Remote Leadership",
  "Remote Negotiation",
  "Remote Problem Solving",
  "Remote Time Management",
  "Renewable Energy",
  "Resilience",
  "Resourcefulness",
  "REST API",
  "RESTful Services",
  "Retail Audit",
  "Retail Compliance",
  "Retail Consulting",
  "Retail Engineering",
  "Retail Management",
  "Retail Marketing",
  "Retail Operations",
  "Retail Planning",
  "Retail Regulation",
  "Retail Risk Management",
  "Retail Sales",
  "Retail Standards",
  "Retail Strategy",
  "Revenue Forecasting",
  "Revenue Growth",
  "Revenue Operations",
  "Risk Assessment",
  "Risk Management",
  "Robotic Process Automation",
  "Robotics Engineering",
  "ROI Analysis",
  "Root Cause Analysis",
  "Route 53",
  "Ruby",
  "Ruby on Rails",
  "Ruby on Rails Development",
  "Ruby Programming",
  "Rust",
  "Rust Programming",
  "SaaS Architecture",
  "Sales Analytics",
  "Sales Enablement",
  "Sales Forecasting",
  "Sales Management",
  "Sales Operations",
  "Sales Pipeline Management",
  "Sales Presentations",
  "Sales Process Optimization",
  "Sales Strategy",
  "Salesforce",
  "Salesforce Administration",
  "Salesforce Development",
  "SAP ERP",
  "Scala",
  "Scala Programming",
  "Scalable API",
  "Scalable Application",
  "Scalable Backend",
  "Scalable Cloud",
  "Scalable Data",
  "Scalable Database",
  "Scalable DevOps",
  "Scalable Frontend",
  "Scalable Infrastructure",
  "Scalable Machine Learning",
  "Scalable Mobile",
  "Scalable Network",
  "Scalable Platform",
  "Scalable Security",
  "Scalable Software",
  "Scalable System",
  "Scalable Web",
  "Scikit-learn",
  "Scriptwriting",
  "Scrum",
  "Scrum Master",
  "SDLC",
  "Search Engine Marketing",
  "Search Engine Optimization",
  "Secure API",
  "Secure Application",
  "Secure Backend",
  "Secure Cloud",
  "Secure Data",
  "Secure Database",
  "Secure DevOps",
  "Secure Frontend",
  "Secure Infrastructure",
  "Secure Machine Learning",
  "Secure Mobile",
  "Secure Network",
  "Secure Platform",
  "Secure Security",
  "Secure Software",
  "Secure System",
  "Secure Web",
  "Securities Law",
  "Security Architecture",
  "Security Auditing",
  "Security Automation",
  "Security Engineering",
  "Security Integration",
  "Security Monitoring",
  "Security Operations",
  "Security Optimization",
  "Security Platform Engineering",
  "Security Troubleshooting",
  "Selenium",
  "Self-Awareness",
  "Self-Motivation",
  "SEM",
  "SEO",
  "Serverless Computing",
  "Service Delivery Management",
  "ServiceNow",
  "Shell",
  "Shell Programming",
  "Shell Scripting",
  "Shopify Development",
  "Site Reliability Engineering",
  "Six Sigma",
  "Sketch",
  "Sketching",
  "Slack",
  "Snowflake",
  "Snowflake Administration",
  "SOC 2 Compliance",
  "Social Art Direction",
  "Social Copywriting",
  "Social Design",
  "Social Direction",
  "Social Illustration",
  "Social Media Content",
  "Social Media Marketing",
  "Social Media Strategy",
  "Social Photography",
  "Social Production",
  "Social Storytelling",
  "Social Strategy",
  "Social Writing",
  "Software Architecture",
  "Software Automation",
  "Software Design Patterns",
  "Software Engineering",
  "Software Integration",
  "Software Monitoring",
  "Software Operations",
  "Software Optimization",
  "Software Platform Engineering",
  "Software Testing",
  "Software Troubleshooting",
  "Software Validation",
  "Solidity",
  "Sound Design",
  "Speech Therapy",
  "Splunk",
  "Spring Boot",
  "Spring Boot Development",
  "SQL",
  "SQL Programming",
  "SQLite",
  "SQLite Administration",
  "SSIS",
  "SSRS",
  "Stakeholder Collaboration",
  "Stakeholder Communication",
  "Stakeholder Decision Making",
  "Stakeholder Leadership",
  "Stakeholder Management",
  "Stakeholder Negotiation",
  "Stakeholder Problem Solving",
  "Stakeholder Time Management",
  "Startup Operations",
  "Storyboarding",
  "Storytelling",
  "Strategic Alliances",
  "Strategic Analytics",
  "Strategic Budgeting",
  "Strategic Compliance",
  "Strategic Consulting",
  "Strategic Development",
  "Strategic Enablement",
  "Strategic Excellence",
  "Strategic Governance",
  "Strategic Growth",
  "Strategic Insights",
  "Strategic Intelligence",
  "Strategic Management",
  "Strategic Operations",
  "Strategic Optimization",
  "Strategic Performance",
  "Strategic Planning",
  "Strategic Reporting",
  "Strategic Strategy",
  "Strategic Thinking",
  "Strategic Transformation",
  "Strategy Consulting",
  "Stress Management",
  "Structural Engineering",
  "Supply Chain Analytics",
  "Supply Chain Management",
  "Surgical Assistance",
  "Sustainability Reporting",
  "Svelte",
  "Svelte Development",
  "Swift",
  "Swift Programming",
  "Symfony",
  "Symfony Development",
  "System Architecture",
  "System Automation",
  "System Design",
  "System Engineering",
  "System Integration",
  "System Monitoring",
  "System Operations",
  "System Optimization",
  "System Platform Engineering",
  "System Troubleshooting",
  "Tableau",
  "Tailwind CSS",
  "Talent Acquisition",
  "Talent Management",
  "Tax Compliance",
  "Tax Planning",
  "Team Building",
  "Team Collaboration",
  "Team Communication",
  "Team Decision Making",
  "Team Leadership",
  "Team Negotiation",
  "Team Problem Solving",
  "Team Time Management",
  "Teamwork",
  "Technical Writing",
  "Telecom Audit",
  "Telecom Compliance",
  "Telecom Consulting",
  "Telecom Engineering",
  "Telecom Management",
  "Telecom Marketing",
  "Telecom Operations",
  "Telecom Planning",
  "Telecom Regulation",
  "Telecom Risk Management",
  "Telecom Sales",
  "Telecom Standards",
  "Telecom Strategy",
  "Telehealth",
  "TensorFlow",
  "Teradata",
  "Teradata Administration",
  "Terraform",
  "Territory Management",
  "Test Automation",
  "Test-Driven Development",
  "Time Management",
  "TimescaleDB",
  "TimescaleDB Administration",
  "Total Quality Management",
  "Toxicology",
  "Trade Marketing",
  "Traffic Engineering",
  "Training and Development",
  "Transportation Audit",
  "Transportation Compliance",
  "Transportation Consulting",
  "Transportation Engineering",
  "Transportation Management",
  "Transportation Marketing",
  "Transportation Operations",
  "Transportation Planning",
  "Transportation Regulation",
  "Transportation Risk Management",
  "Transportation Sales",
  "Transportation Standards",
  "Transportation Strategy",
  "Trello",
  "Turnaround Management",
  "TypeScript",
  "TypeScript Programming",
  "Typography",
  "UI Design",
  "UI Development",
  "Underwriting",
  "Unit Testing",
  "Unity",
  "Unreal Engine",
  "Urban Planning",
  "Utilities Audit",
  "Utilities Compliance",
  "Utilities Consulting",
  "Utilities Engineering",
  "Utilities Management",
  "Utilities Marketing",
  "Utilities Operations",
  "Utilities Planning",
  "Utilities Regulation",
  "Utilities Risk Management",
  "Utilities Sales",
  "Utilities Standards",
  "Utilities Strategy",
  "Utility Management",
  "UX Design",
  "UX Engineering",
  "UX Research",
  "UX Writing",
  "Validation Engineering",
  "Value Proposition Design",
  "VB.NET",
  "VB.NET Programming",
  "Vendor Management",
  "Venture Capital",
  "Version Control",
  "Veterinary Medicine",
  "Video Editing",
  "Video Production",
  "Virtual Collaboration",
  "Virtual Communication",
  "Virtual Decision Making",
  "Virtual Leadership",
  "Virtual Negotiation",
  "Virtual Problem Solving",
  "Virtual Time Management",
  "Virtualization",
  "Visual Art Direction",
  "Visual Basic",
  "Visual Basic Programming",
  "Visual Copywriting",
  "Visual Design",
  "Visual Direction",
  "Visual Illustration",
  "Visual Merchandising",
  "Visual Photography",
  "Visual Production",
  "Visual Storytelling",
  "Visual Strategy",
  "Visual Studio Code",
  "Visual Writing",
  "VMware",
  "VPC Networking",
  "VS Code",
  "Vue.js",
  "Vue.js Development",
  "Water Treatment",
  "Wealth Management",
  "Web Accessibility",
  "Web Architecture",
  "Web Art Direction",
  "Web Automation",
  "Web Copywriting",
  "Web Design",
  "Web Development",
  "Web Direction",
  "Web Engineering",
  "Web Illustration",
  "Web Integration",
  "Web Monitoring",
  "Web Operations",
  "Web Optimization",
  "Web Performance",
  "Web Photography",
  "Web Platform Engineering",
  "Web Production",
  "Web Security",
  "Web Storytelling",
  "Web Strategy",
  "Web Troubleshooting",
  "Web Writing",
  "Webpack",
  "WebSockets",
  "Windows Server Administration",
  "Wireframing",
  "WordPress Development",
  "Work Ethic",
  "Workers Compensation",
  "Workflow Optimization",
  "Workforce Planning",
  "Written Communication",
  "XML",
  "YAML",
  "Zapier",
  "Zero Trust Security",

  // === Tools — Project Management ===
  "Asana",
  "Basecamp",
  "ClickUp",
  "Linear",
  "Monday.com",
  "Smartsheet",
  "Wrike",

  // === Tools — CRM & Marketing Automation ===
  "ActiveCampaign",
  "HubSpot",
  "HubSpot CRM",
  "HubSpot Marketing",
  "Intercom",
  "Klaviyo",
  "Mailchimp",
  "Marketo",
  "Pardot",
  "Pipedrive",
  "Zoho CRM",

  // === Tools — Analytics & BI ===
  "Amplitude",
  "Freshdesk",
  "Google Analytics",
  "Google Ads",
  "Google Tag Manager",
  "Heap Analytics",
  "Hotjar",
  "LinkedIn Ads",
  "Looker",
  "Meta Ads",
  "Mixpanel",
  "Mode Analytics",
  "Segment",
  "Sigma Computing",
  "Zendesk",

  // === Tools — Design & Prototyping ===
  "Balsamiq",
  "Framer",
  "InVision",
  "Lucidchart",
  "Miro",
  "Principle",
  "ProtoPie",
  "Webflow",
  "Zeplin",

  // === Tools — Finance & Accounting ===
  "NetSuite",
  "Oracle Financials",
  "QuickBooks",
  "Workday Financials",
  "Xero",

  // === Tools — HR & People Systems ===
  "ADP",
  "BambooHR",
  "Greenhouse",
  "Lever",
  "SAP SuccessFactors",
  "Workday",
  "Workday HCM",

  // === Tools — DevOps & Infrastructure ===
  "ArgoCD",
  "AWS CDK",
  "Cilium",
  "Crossplane",
  "Istio",
  "k3s",
  "Linkerd",
  "Pulumi",
  "Rancher",

  // === Tools — Testing ===
  "Appium",
  "Apache JMeter",
  "Cypress",
  "k6",
  "Locust",
  "Playwright",
  "Puppeteer",
  "TestRail",
  "WebdriverIO",

  // === Tools — AI / ML ===
  "AWS Bedrock",
  "Chroma",
  "DVC",
  "GitHub Copilot",
  "LangGraph",
  "LlamaIndex",
  "MLflow",
  "ONNX",
  "Pinecone",
  "Qdrant",
  "Ray",
  "Triton Inference Server",
  "Vertex AI",
  "Weaviate",
  "Weights & Biases",

  // === Tools — Communication & Collaboration ===
  "Loom",
  "Microsoft Teams",
  "Zoom",

  // === AI Skills ===
  "Agentic AI",
  "AI Ethics",
  "AI Governance",
  "AI Literacy",
  "AI Product Management",
  "Fine-Tuning",
  "Generative AI",
  "LLM Development",
  "Model Evaluation",
  "RAG",
  "Responsible AI",
  "Retrieval-Augmented Generation",
  "Vector Databases",
  "Vector Search",

  // === Soft Skills (missing) ===
  "Cognitive Flexibility",
  "Complex Problem Solving",
  "Conflict Mitigation",
  "Cultural Intelligence",
  "Digital Fluency",
  "First Principles Thinking",
  "Inclusive Leadership",
  "Influence Without Authority",
  "Intellectual Curiosity",
  "Multitasking",
  "Organization",
  "People Management",
  "Self-Direction",
  "Service Orientation",
  "Situational Awareness",
  "Synthesis",
  "Systems Thinking",
  "Thought Leadership",

  // === Marketing Skills ===
  "Account-Based Marketing",
  "Affiliate Marketing",
  "Attribution Modeling",
  "Churn Reduction",
  "Conversion Rate Optimization",
  "Customer Acquisition Cost",
  "Customer Lifetime Value",
  "Event Marketing",
  "Growth Marketing",
  "Influencer Marketing",
  "Lifecycle Marketing",
  "Media Planning",
  "Multi-Channel Marketing",
  "Paid Social",
  "Performance Marketing",
  "Product-Led Growth",
  "Programmatic Advertising",
  "Retargeting",
  "Revenue Marketing",
  "Video Marketing",

  // === Sales Skills ===
  "Account Planning",
  "Business Acumen",
  "Cold Calling",
  "Cold Emailing",
  "Consultative Selling",
  "Customer Discovery",
  "Deal Management",
  "Discovery Calls",
  "MEDDIC",
  "MEDDPICC",
  "Objection Handling",
  "Relationship Selling",
  "Revenue Intelligence",
  "Sales Intelligence",
  "Sales Methodology",
  "Solution Selling",
  "Solution-Based Selling",
  "SPIN Selling",
  "Value-Based Selling",
  "Virtual Selling",

  // === Finance & Accounting Skills ===
  "Bookkeeping",
  "Capital Budgeting",
  "Cash Flow Forecasting",
  "Consolidation Accounting",
  "FCPA Compliance",
  "Financial Close",
  "FP&A",
  "GAAP",
  "IFRS",
  "Month-End Close",
  "Revenue Recognition",
  "SOX Compliance",
  "Tax Returns",
  "Treasury Management",
  "Variance Analysis",
  "Working Capital Management",

  // === HR & People Skills ===
  "Benefits Administration",
  "Compensation Planning",
  "Employee Engagement",
  "Employee Experience",
  "Employer Branding",
  "HR Information Systems",
  "Job Architecture",
  "Learning Management Systems",
  "Offboarding",
  "Onboarding",
  "Pay Equity Analysis",
  "People Analytics",
  "Performance Reviews",
  "Succession Planning",
  "Talent Mapping",
  "Workforce Analytics",
  "Workplace Culture",

  // === Legal & Compliance Skills ===
  "Arbitration",
  "Compliance Program Management",
  "Contract Drafting",
  "Contract Review",
  "Data Protection",
  "eDiscovery",
  "Employment Law",
  "Legal Entity Management",
  "Policy Development",
  "Privacy Law",
  "Regulatory Submissions",
  "Trade Law",

  // === Operations & Supply Chain Skills ===
  "Continuous Improvement",
  "Demand Sensing",
  "Global Sourcing",
  "Import/Export Compliance",
  "Inventory Optimization",
  "Just-In-Time Manufacturing",
  "Kaizen",
  "Lean Manufacturing",
  "MRP Systems",
  "Order Fulfillment",
  "Process Documentation",
  "Quality Management Systems",
  "S&OP Planning",
  "Supplier Management",
  "Supplier Negotiation",
  "Value Stream Mapping",
  "Warehouse Management",
  "Vendor Evaluation",

  // === Data & Analytics Skills ===
  "Cohort Analysis",
  "Data Cleaning",
  "Data Ethics",
  "Data Literacy",
  "Data Migration",
  "Data Products",
  "Data Storytelling",
  "Data Strategy",
  "Experiment Design",
  "Funnel Analysis",
  "KPI Frameworks",
  "Metrics Definition",
  "Statistical Analysis",
  "Statistical Modeling",
  "Survey Design",

  // === Healthcare Skills ===
  "Care Coordination",
  "Clinical Decision Making",
  "Clinical Documentation",
  "Clinical Informatics",
  "Electronic Health Records",
  "Epic",
  "Health Coaching",
  "Medical Billing",
  "Patient Assessment",
  "Patient Education",
  "Patient Safety",
  "Population Health",
  "Quality Improvement",

  // === Engineering & Technical ===
  "API-First Design",
  "CQRS",
  "Developer Experience",
  "Developer Relations",
  "Event-Driven Architecture",
  "Event Sourcing",
  "Platform Thinking",
  "Technical Evangelism",
  "Technical Roadmapping",
] as const;

export type MasterSkill = (typeof MASTER_SKILLS)[number];

/** Fuzzy-ranked skill suggestions for Studio autocomplete. */
export function fuzzySearchMasterSkills(query: string, limit = 10): string[] {
  const trimmed = query.trim();
  if (!trimmed) return [...MASTER_SKILLS].slice(0, limit);

  return [...MASTER_SKILLS]
    .map((skill) => ({ skill, score: fuzzyMatchScore(skill, trimmed) }))
    .filter((entry) => entry.score >= 0)
    .sort((a, b) => b.score - a.score || a.skill.localeCompare(b.skill))
    .slice(0, limit)
    .map((entry) => entry.skill);
}

export function isExactMasterSkill(input: string): boolean {
  const trimmed = input.trim().toLowerCase();
  if (!trimmed) return false;
  return MASTER_SKILLS.some((skill) => skill.toLowerCase() === trimmed);
}
