/**
 * Backward-compatible re-exports — prefer `@/src/lib/config/app.config` for new code.
 */
export {
  AI_MODELS_CACHE_KEY,
  AI_PROVIDERS,
  ALL_AI_PROVIDERS,
  APP_RUNTIME,
  appConfig,
  buildDefaultModelCatalog,
  DEFAULT_AI_MODELS_UPDATE_HOURS,
  getDefaultModelsForProvider,
  getMaxTokenBuffer,
  getProviderChatUrl,
  getProviderConfig,
  getProviderDocumentationUrl,
  getProviderHandshakeUrl,
  getProviderIconRef,
  getProviderModelsUrl,
  getProviderRegistryEntry,
  getServiceEntry,
  getTargetAiModel,
  isAiProvider,
  PROVIDER_REGISTRY,
  SERVICE_REGISTRY,
  SYSTEM_DEFAULTS,
  type AiModelsCache,
  type AiProvider,
  type LegacyAppConfig as AppConfig,
  type ProviderConfig,
  type ProviderIconRef,
  type ProviderRegistryEntry,
  type ServiceRegistryEntry,
  type SystemDefaults,
} from "@/src/lib/config/app.config";
